export const recipes = {
  recipe_moon_latte: { id: 'recipe_moon_latte', name: '月光花瓣拿鐵', station: 'kitchen', category: 'drink', unlockRequirement: { level: 1, station: 'kitchen' }, cost: { moon_petals: 1, stardew_water: 1 }, output: { itemId: 'moon_latte', qty: 1 }, description: '把月光花瓣泡進星露水裡，再加入柔和奶泡，做成安定系飲品。' },
  recipe_star_berry_tart: { id: 'recipe_star_berry_tart', name: '星星莓奶油塔', station: 'kitchen', category: 'sweet', unlockRequirement: { level: 1, station: 'kitchen' }, cost: { star_berry: 2, forest_cookie: 1 }, output: { itemId: 'star_berry_tart', qty: 1 }, description: '把森林餅乾壓成塔皮，鋪上星星莓與奶油，做成會掉金色糖屑的小塔。' },
  recipe_dream_cocoa: { id: 'recipe_dream_cocoa', name: '夜空碎片可可', station: 'kitchen', category: 'drink', unlockRequirement: { level: 2, station: 'kitchen' }, cost: { night_sky_fragment: 1, stardew_water: 1 }, output: { itemId: 'dream_cocoa', qty: 1 }, description: '把夜空碎片溶進熱可可，讓杯面浮出一片安靜的星空。' },

  recipe_moon_dew: { id: 'recipe_moon_dew', name: '月光露珠', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { moon_petals: 1, stardew_water: 1 }, output: { itemId: 'moon_dew', qty: 1 }, description: '把月光花瓣與星露水低溫煉成透明露珠，是月光系商品的基礎素材。' },
  recipe_star_berry_syrup: { id: 'recipe_star_berry_syrup', name: '星莓糖漿', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { star_berry: 2, stardew_water: 1 }, output: { itemId: 'star_berry_syrup', qty: 1 }, description: '把星星莓熬成帶有星屑感的糖漿，是甜點與飲品的常用煉成素材。' },
  recipe_dream_essence: { id: 'recipe_dream_essence', name: '夢境精華', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { night_sky_fragment: 1, stardew_water: 1 }, output: { itemId: 'dream_essence', qty: 1 }, description: '讓夜空碎片在星露水中沉澱，提取出安靜的夢境精華。' },
  recipe_pure_moon_essence: { id: 'recipe_pure_moon_essence', name: '純月精華', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 3, station: 'alchemy' }, cost: { moon_dew: 1, night_sky_fragment: 1 }, output: { itemId: 'pure_moon_essence', qty: 1 }, description: '將月光露珠與夜空碎片再次穩定化，煉成高階月光與夢境商品使用的三階素材。' },

  recipe_neutralizer: { id: 'recipe_neutralizer', name: '溫和中和劑', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { ghostlight_dew_bead: 1, milk_dew: 2 }, output: { itemId: 'neutralizer', qty: 1 }, description: '幽光露水珠與牛奶露珠萃取成能融合不同魔力的溶劑。' },
  recipe_ice_fire_solution: { id: 'recipe_ice_fire_solution', name: '冰火調和液', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { ice_breath_essence: 2, volcanic_lava_honey: 1 }, output: { itemId: 'ice_fire_solution', qty: 1 }, description: '將極寒晶粹與火山熔岩蜜轉化成不斷翻滾的冰火液體。' },
  recipe_growth_essence: { id: 'recipe_growth_essence', name: '萬物生長精華', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 3, station: 'alchemy' }, cost: { neutralizer: 2, dawn_jam_berry: 1, oasis_dew: 1 }, output: { itemId: 'growth_essence', qty: 1 }, description: '跨區調和森林晨曦與沙漠沙洲露，煉成枯木逢春的頂級精華。' },

  recipe_frost_steel_ingot: { id: 'recipe_frost_steel_ingot', name: '霜鋼錠', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { cold_iron_ore: 2, rough_crystal: 2 }, output: { itemId: 'frost_steel_ingot', qty: 1 }, description: '以寒鐵與粗糙水晶鍛造成表面結霜的鋼錠。' },
  recipe_hot_mithril: { id: 'recipe_hot_mithril', name: '熾熱秘銀', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { mithril_ore: 2, coal_fragment: 3 }, output: { itemId: 'hot_mithril', qty: 1 }, description: '秘銀礦石與煤炭碎片鍛造成耐高溫的紅光秘銀。' },
  recipe_star_glass_gold: { id: 'recipe_star_glass_gold', name: '星空琉璃金', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 3, station: 'alchemy' }, cost: { hot_mithril: 2, glass_mithril: 1, eternal_ice_core: 1 }, output: { itemId: 'star_glass_gold', qty: 1 }, description: '將火、冰與琉璃秘銀結晶成王族級金屬。' },

  recipe_rotproof_wood: { id: 'recipe_rotproof_wood', name: '韌性防腐木', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { hard_oak: 2, slime_mucus_grass: 2 }, output: { itemId: 'rotproof_wood', qty: 1 }, description: '硬質橡木塗上史萊姆膠後轉化成防水防腐建材。' },
  recipe_glowing_magic_brick: { id: 'recipe_glowing_magic_brick', name: '透光魔力磚', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { white_crystal_sand: 3, golden_sand: 2 }, output: { itemId: 'glowing_magic_brick', qty: 1 }, description: '白水晶砂與黃金沙粒結晶成白天吸光、夜晚發亮的磚。' },
  recipe_world_tree_board: { id: 'recipe_world_tree_board', name: '世界樹庇護板', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 3, station: 'alchemy' }, cost: { rotproof_wood: 2, forest_heartwood: 1, mist_core: 1 }, output: { itemId: 'world_tree_board', qty: 1 }, description: '以森林之心與迷霧之核附魔的頂級木板。' },

  recipe_stardust_warm_cloth: { id: 'recipe_stardust_warm_cloth', name: '星塵保溫布', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { frost_cotton_snowball: 2, dandelion_fluff: 2 }, output: { itemId: 'stardust_warm_cloth', qty: 1 }, description: '寒霜棉花雪球與蒲公英絨轉化成會調節溫度的布料。' },
  recipe_heatproof_cactus_thread: { id: 'recipe_heatproof_cactus_thread', name: '耐熱仙人掌線', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { hardened_cactus_fiber: 3, soft_vine: 2 }, output: { itemId: 'heatproof_cactus_thread', qty: 1 }, description: '硬化仙人掌纖維與柔軟藤蔓萃取成耐火線材。' },
  recipe_phantom_starry_cloth: { id: 'recipe_phantom_starry_cloth', name: '幻影星空布', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 3, station: 'alchemy' }, cost: { stardust_warm_cloth: 2, heatproof_cactus_thread: 1, sun_fragment: 1 }, output: { itemId: 'phantom_starry_cloth', qty: 1 }, description: '星塵保溫布、耐熱線與太陽碎片附魔成傳說布料。' },
  recipe_magic_rope: { id: 'recipe_magic_rope', name: '魔法編織繩', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { soft_vine: 2, tough_reed: 1 }, output: { itemId: 'magic_rope', qty: 1 }, description: '把藤蔓與韌性蘆葦轉化成能承載空間魔法的編織繩。' },
  recipe_strong_cactus_cloth: { id: 'recipe_strong_cactus_cloth', name: '強韌仙人掌布', station: 'alchemy', category: 'refined_material', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { hardened_cactus_fiber: 2, heatproof_cactus_thread: 1 }, output: { itemId: 'strong_cactus_cloth', qty: 1 }, description: '用耐熱仙人掌線與纖維織成耐磨布料。' },

  recipe_dawn_jam_berry_tart: { id: 'recipe_dawn_jam_berry_tart', name: '晨曦果醬莓果塔', station: 'kitchen', category: 'sweet', unlockRequirement: { level: 2, station: 'kitchen' }, cost: { melon_bun_fruit: 2, volcanic_lava_honey: 1, dawn_jam_berry: 1 }, output: { itemId: 'dawn_jam_berry_tart', qty: 1 }, description: '以蜜瓜小麵包果、火山熔岩蜜與晨曦果醬莓烘焙成高階莓果塔。' },
  recipe_mint_starry_soda: { id: 'recipe_mint_starry_soda', name: '薄荷星空氣泡飲', station: 'kitchen', category: 'drink', unlockRequirement: { level: 1, station: 'kitchen' }, cost: { ice_breath_essence: 2, mint_snowcap_grass: 1 }, output: { itemId: 'mint_starry_soda', qty: 1 }, description: '冰息晶粹與薄荷雪頂草冰鎮成會吐出星光冰息的飲料。' },
  recipe_lava_pancake: { id: 'recipe_lava_pancake', name: '熔岩爆漿鬆餅', station: 'kitchen', category: 'sweet', unlockRequirement: { level: 2, station: 'kitchen' }, cost: { melon_bun_fruit: 2, lava_popcorn_stone: 1, milk_dew: 1 }, output: { itemId: 'lava_pancake', qty: 1 }, description: '切開會流出甜蜜岩漿的火山鬆餅。' },
  recipe_rainbow_parfait: { id: 'recipe_rainbow_parfait', name: '終極大滿貫彩虹百匯', station: 'kitchen', category: 'sweet', unlockRequirement: { level: 3, station: 'kitchen' }, cost: { ice_candy_fruit: 1, star_gummy_fruit: 2, cactus_sugar: 1, blueberry_sorbet_fruit: 1 }, output: { itemId: 'rainbow_parfait', qty: 1 }, description: '以滿載五份素材裝飾成終極夢幻冰品。' },

  recipe_warm_display_case: { id: 'recipe_warm_display_case', name: '初級保溫展示櫃', station: 'alchemy', category: 'product', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { frost_steel_ingot: 1, glowing_magic_brick: 2, soft_vine: 1 }, output: { itemId: 'warm_display_case', qty: 1 }, description: '用霜鋼錠與透光魔力磚製作能保溫的展示櫃。' },
  recipe_portable_gather_bag: { id: 'recipe_portable_gather_bag', name: '便攜採集藤編包', station: 'alchemy', category: 'product', unlockRequirement: { level: 2, station: 'alchemy' }, cost: { magic_rope: 2, strong_cactus_cloth: 1, soft_vine: 2 }, output: { itemId: 'portable_gather_bag', qty: 1 }, description: '以魔法編織繩、仙人掌布與藤蔓轉化成可擴充背包的採集包。' },
  recipe_cleansing_incense_lamp: { id: 'recipe_cleansing_incense_lamp', name: '淨化薰香燈', station: 'alchemy', category: 'product', unlockRequirement: { level: 3, station: 'alchemy' }, cost: { rough_crystal: 2, neutralizer: 1, mist_core: 1 }, output: { itemId: 'cleansing_incense_lamp', qty: 1 }, description: '粗糙水晶、溫和中和劑與迷霧之核附魔成淨化家具。' },
};
