export const items = {
  moon_petals: { id: 'moon_petals', name: '月光花瓣', icon: '🌙', type: 'material', typeName: '素材', rarity: 'SR', stars: 5, source: ['簽到', '祈願', '溫室'], use: '提升藥水純度、製作月光系飲品。', description: '只在滿月之夜綻放的花朵所掉落的花瓣，吸收了月光後會微微發亮。常被用於提升藥水的純度與安定性，也象徵溫柔與祝福。' },
  star_berry: { id: 'star_berry', name: '星星莓', icon: '🍓', type: 'material', typeName: '素材', rarity: 'R', stars: 4, source: ['簽到', '祈願', '後山'], use: '加入甜點或飲品，增加好運與活力。', description: '生長在魔力濃厚地區的莓果，果皮上自然形成金箔斑點。味道甜中帶微酸，常被加入甜點或飲品中，象徵好運與活力。' },
  night_sky_fragment: { id: 'night_sky_fragment', name: '夜空碎片', icon: '🌌', type: 'material', typeName: '素材', rarity: 'SR', stars: 5, source: ['祈願'], use: '夜晚、夢境或情緒相關魔法商品。', description: '夜晚天空中掉落的碎片，彷彿封存了一小段星空。常用於與夜晚、夢境或情緒相關的魔法。' },
  forest_cookie: { id: 'forest_cookie', name: '森林餅乾', icon: '🍪', type: 'sweet', typeName: '甜點', rarity: 'R', stars: 2, source: ['祈願', '後山'], use: '普通委託常見小甜點。', description: '烤成葉片形狀的小餅乾，帶著淡淡蜂蜜與木質香。' },
  stardew_water: { id: 'stardew_water', name: '星露水', icon: '💧', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['祈願', '簽到', '後山', '溫室'], use: '澆灌魔法植物，或作為飲品與煉成基底。', description: '清晨凝在花瓣上的露水，映著細小星光。' },

  melon_bun_fruit: { id: 'melon_bun_fruit', name: '蜜瓜小麵包果', icon: '🍈', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['繁茂森林'], use: '烘焙甜點基底。', description: '長得像小麵包的森林果實，外皮帶有蜜瓜般的甜香。' },
  star_gummy_fruit: { id: 'star_gummy_fruit', name: '星星軟糖果', icon: '⭐', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['繁茂森林'], use: '甜點裝飾與彩虹系冰品。', description: '像軟糖一樣Q彈的星形果實。' },
  crunchy_hazelnut_crisp: { id: 'crunchy_hazelnut_crisp', name: '脆脆榛果酥', icon: '🌰', type: 'material', typeName: '食物素材', rarity: 'R', stars: 3, source: ['繁茂森林'], use: '增加甜點酥脆口感。', description: '森林榛果自然烘烤形成的酥脆碎片。' },
  dawn_jam_berry: { id: 'dawn_jam_berry', name: '晨曦果醬莓', icon: '🫐', type: 'material', typeName: '食物素材', rarity: 'SR', stars: 5, source: ['繁茂森林'], use: '高階莓果塔與生長系煉金。', description: '清晨才會成熟的果醬莓，切開時會流出日出色果醬。' },
  soft_vine: { id: 'soft_vine', name: '柔軟藤蔓', icon: '🌿', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['繁茂森林'], use: '建材、背包、裝飾與煉金配方。', description: '柔軟但不易斷裂的森林藤蔓。' },
  tender_leaf_grass: { id: 'tender_leaf_grass', name: '嫩葉草', icon: '🌱', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['繁茂森林'], use: '基礎草本材料。', description: '新長出的嫩葉草，帶著溫和生命力。' },
  tough_bark: { id: 'tough_bark', name: '韌性樹皮', icon: '🪵', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['繁茂森林'], use: '防腐木與結構補強。', description: '富有彈性的樹皮，適合處理成耐用建材。' },
  hard_oak: { id: 'hard_oak', name: '硬質橡木', icon: '🪵', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['繁茂森林'], use: '魔法木材與家具基底。', description: '質地堅硬的橡木，能承受煉金加工。' },
  forest_heartwood: { id: 'forest_heartwood', name: '森林之心（活木）', icon: '💚', type: 'rare_material', typeName: '結構素材', rarity: 'SR', stars: 5, source: ['繁茂森林'], use: '頂級魔法木材核心。', description: '仍保有生命脈動的活木核心。' },
  milk_dew: { id: 'milk_dew', name: '牛奶露珠', icon: '🥛', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['繁茂森林'], use: '溶液、鬆餅與飲品基底。', description: '帶著奶香的白色露珠，適合讓魔力變得溫和。' },
  dandelion_fluff: { id: 'dandelion_fluff', name: '輕飄飄蒲公英絨', icon: '🪽', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['繁茂森林'], use: '柔軟布料與保溫素材。', description: '幾乎沒有重量的蒲公英絨毛。' },

  ice_candy_fruit: { id: 'ice_candy_fruit', name: '碎冰糖心果', icon: '🧊', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['冰封雪山'], use: '冰品、氣泡飲與彩虹百匯。', description: '果肉像碎冰糖一樣閃亮。' },
  mint_snowcap_grass: { id: 'mint_snowcap_grass', name: '薄荷雪頂草', icon: '🌿', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['冰封雪山'], use: '冰鎮飲品與清涼料理。', description: '葉尖覆著薄雪的薄荷草。' },
  frost_cotton_snowball: { id: 'frost_cotton_snowball', name: '寒霜棉花雪球', icon: '☁️', type: 'material', typeName: '食物素材', rarity: 'R', stars: 3, source: ['冰封雪山'], use: '布料、冷飲與雪系甜點。', description: '像棉花糖一樣柔軟的雪球。' },
  blueberry_sorbet_fruit: { id: 'blueberry_sorbet_fruit', name: '藍莓雪酪果', icon: '🫐', type: 'material', typeName: '食物素材', rarity: 'SR', stars: 5, source: ['冰封雪山'], use: '頂級冰品與彩虹百匯。', description: '入口即化的冰涼莓果。' },
  ice_breath_essence: { id: 'ice_breath_essence', name: '冰息晶粹', icon: '❄️', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['冰封雪山'], use: '冰鎮飲品與冰火調和液。', description: '凝固成晶體的寒冷吐息。' },
  ice_crystal_dew: { id: 'ice_crystal_dew', name: '冰晶露珠', icon: '💧', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['冰封雪山'], use: '冷卻、結晶與藥水。', description: '透明如冰晶的露珠。' },
  frozen_resin: { id: 'frozen_resin', name: '凍結樹脂', icon: '🧊', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['冰封雪山'], use: '黏合、保溫與防腐處理。', description: '低溫凝固的透明樹脂。' },
  snow_pine_twig: { id: 'snow_pine_twig', name: '雪松細枝', icon: '🌲', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['冰封雪山'], use: '雪山系家具與建材。', description: '帶著雪香的松木細枝。' },
  white_birch_bark: { id: 'white_birch_bark', name: '白樺白皮', icon: '📜', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['冰封雪山'], use: '紙材、裝飾與結構包覆。', description: '雪白的白樺樹皮。' },
  cold_iron_ore: { id: 'cold_iron_ore', name: '寒鐵礦石', icon: '⛓️', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['冰封雪山'], use: '霜鋼錠與設備升級。', description: '摸起來永遠冰冷的礦石。' },
  eternal_ice_core: { id: 'eternal_ice_core', name: '永恆冰芯', icon: '🧊', type: 'rare_material', typeName: '結構素材', rarity: 'SR', stars: 5, source: ['冰封雪山'], use: '高階合金核心。', description: '不會融化的冰之核心。' },

  dreamy_bubble_mushroom: { id: 'dreamy_bubble_mushroom', name: '迷幻泡泡菇', icon: '🍄', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['迷霧沼澤'], use: '奇幻料理與夢境系配方。', description: '會吹出小泡泡的沼澤蘑菇。' },
  mud_rainbow_bamboo: { id: 'mud_rainbow_bamboo', name: '泥潭彩虹筍', icon: '🎋', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['迷霧沼澤'], use: '彩色料理與特殊配方。', description: '從泥潭裡長出的彩色竹筍。' },
  ghostlight_dew_bead: { id: 'ghostlight_dew_bead', name: '幽光露水珠', icon: '🔮', type: 'material', typeName: '食物素材', rarity: 'R', stars: 3, source: ['迷霧沼澤'], use: '溫和中和劑與沼澤飲品。', description: '在霧裡發出幽光的露水珠。' },
  wisteria_dew_berry: { id: 'wisteria_dew_berry', name: '紫藤露水莓', icon: '🫐', type: 'material', typeName: '食物素材', rarity: 'SR', stars: 5, source: ['迷霧沼澤'], use: '高階甜點與夢境料理。', description: '沾著紫藤香氣的露水莓。' },
  slime_mucus_grass: { id: 'slime_mucus_grass', name: '史萊姆黏液草', icon: '🟢', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['迷霧沼澤'], use: '防腐木、轉化與黏合劑。', description: '帶有天然史萊姆膠的草。' },
  sweet_cotton_moss: { id: 'sweet_cotton_moss', name: '甜甜棉花苔', icon: '☁️', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['迷霧沼澤'], use: '柔軟內餡與沼澤甜點。', description: '吃起來像棉花糖的苔蘚。' },
  bubble_marble_fruit: { id: 'bubble_marble_fruit', name: '氣泡彈珠果', icon: '🫧', type: 'material', typeName: '素材', rarity: 'SR', stars: 5, source: ['迷霧沼澤'], use: '氣泡飲與特殊彈珠甜點。', description: '像彈珠一樣會反彈的氣泡果。' },
  rotten_wood: { id: 'rotten_wood', name: '腐木', icon: '🪵', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['迷霧沼澤'], use: '沼澤建材與轉化素材。', description: '潮濕又富含菌絲的腐木。' },
  damp_moss: { id: 'damp_moss', name: '濕潤苔蘚', icon: '🌿', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['迷霧沼澤'], use: '保濕與柔軟建材。', description: '一直保持濕潤的苔蘚。' },
  charred_blackwood: { id: 'charred_blackwood', name: '碳化黑木', icon: '⚫', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['迷霧沼澤'], use: '耐腐建材與黑木家具。', description: '自然碳化卻仍保有韌性的黑木。' },
  tough_reed: { id: 'tough_reed', name: '韌性蘆葦', icon: '🌾', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['迷霧沼澤'], use: '編織與背包素材。', description: '可以彎折卻不易斷裂的蘆葦。' },
  mist_core: { id: 'mist_core', name: '迷霧之核', icon: '🌫️', type: 'rare_material', typeName: '結構素材', rarity: 'SR', stars: 5, source: ['迷霧沼澤'], use: '世界樹庇護板與淨化家具。', description: '凝成核心形狀的濃霧魔力。' },

  lava_popcorn_stone: { id: 'lava_popcorn_stone', name: '熔岩爆米花石', icon: '🍿', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['滾燙火山'], use: '火山甜點與爆漿鬆餅。', description: '加熱後會像爆米花一樣膨起的熔岩石。' },
  hot_strawberry_banana: { id: 'hot_strawberry_banana', name: '炙熱草莓蕉', icon: '🍌', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['滾燙火山'], use: '火山系甜點。', description: '帶著草莓香氣的熱帶香蕉。' },
  chili_popping_candy: { id: 'chili_popping_candy', name: '辣椒跳跳糖', icon: '🌶️', type: 'material', typeName: '食物素材', rarity: 'R', stars: 3, source: ['滾燙火山'], use: '刺激系甜點與料理。', description: '入口會跳動的辛辣糖粒。' },
  roasted_caramel_mushroom: { id: 'roasted_caramel_mushroom', name: '炙烤焦糖菇', icon: '🍄', type: 'material', typeName: '食物素材', rarity: 'SR', stars: 5, source: ['滾燙火山'], use: '高階焦糖料理。', description: '自然烤出焦糖外殼的火山菇。' },
  volcanic_lava_honey: { id: 'volcanic_lava_honey', name: '火山熔岩蜜', icon: '🍯', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['滾燙火山'], use: '果醬塔、冰火調和液與火山甜點。', description: '像熔岩一樣微熱流動的蜂蜜。' },
  fire_crystal_dew: { id: 'fire_crystal_dew', name: '火晶露水珠', icon: '🔥', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['滾燙火山'], use: '火屬性煉金與調味。', description: '封著火焰晶光的露水珠。' },
  coal_fragment: { id: 'coal_fragment', name: '煤炭碎片', icon: '⚫', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['滾燙火山'], use: '熾熱秘銀與鍛造燃料。', description: '穩定燃燒的煤炭碎片。' },
  fire_rock: { id: 'fire_rock', name: '火岩石', icon: '🪨', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['滾燙火山'], use: '耐熱建材。', description: '內部仍帶著火光的岩石。' },
  obsidian: { id: 'obsidian', name: '黑曜石', icon: '⬛', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['滾燙火山'], use: '鍛造與裝飾。', description: '光滑堅硬的黑色火山玻璃。' },
  light_volcanic_ash: { id: 'light_volcanic_ash', name: '輕盈火山灰', icon: '🌋', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['滾燙火山'], use: '耐熱配方與輕量建材。', description: '漂浮感很強的細緻火山灰。' },
  flame_ember: { id: 'flame_ember', name: '火焰餘燼', icon: '🔥', type: 'rare_material', typeName: '結構素材', rarity: 'SR', stars: 5, source: ['滾燙火山'], use: '高階火焰核心素材。', description: '永不完全熄滅的火焰餘燼。' },

  sparkling_raw_fruit: { id: 'sparkling_raw_fruit', name: '閃閃原石果', icon: '💎', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['水晶洞窟'], use: '水晶風味甜點。', description: '外皮像原石一樣閃亮的果實。' },
  glow_gem_berry: { id: 'glow_gem_berry', name: '夜光寶石莓', icon: '💠', type: 'material', typeName: '食物素材', rarity: 'SR', stars: 5, source: ['水晶洞窟'], use: '高階寶石甜點。', description: '夜晚會發光的寶石莓。' },
  rainbow_fluorite: { id: 'rainbow_fluorite', name: '七彩螢石', icon: '🔷', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['水晶洞窟'], use: '結晶與裝飾。', description: '映出七彩光的螢石碎片。' },
  white_crystal_sand: { id: 'white_crystal_sand', name: '白水晶砂', icon: '▫️', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['水晶洞窟'], use: '透光魔力磚與結晶素材。', description: '磨成砂狀的白水晶。' },
  pure_energy_crystal: { id: 'pure_energy_crystal', name: '純淨能量晶', icon: '🔹', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['水晶洞窟'], use: '能量補強與煉金核心。', description: '蘊含純淨能量的小晶體。' },
  rough_crystal: { id: 'rough_crystal', name: '粗糙水晶', icon: '🔶', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['水晶洞窟'], use: '霜鋼錠、薰香燈與結構素材。', description: '尚未打磨的粗糙水晶。' },
  mithril_ore: { id: 'mithril_ore', name: '秘銀礦石', icon: '⛏️', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['水晶洞窟'], use: '熾熱秘銀與高階金屬。', description: '輕盈且魔力導通性高的礦石。' },
  neon_rainbow_stone: { id: 'neon_rainbow_stone', name: '霓虹彩虹石', icon: '🌈', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['水晶洞窟'], use: '彩光裝飾與結晶配方。', description: '發出霓虹般彩光的石頭。' },
  glass_mithril: { id: 'glass_mithril', name: '琉璃秘銀', icon: '🪞', type: 'rare_material', typeName: '結構素材', rarity: 'SR', stars: 5, source: ['水晶洞窟'], use: '星空琉璃金核心素材。', description: '像琉璃一樣透明的秘銀。' },
  star_raw_stone: { id: 'star_raw_stone', name: '星辰原石', icon: '🌟', type: 'rare_material', typeName: '結構素材', rarity: 'SR', stars: 5, source: ['水晶洞窟'], use: '高階星辰煉金。', description: '內部像藏著星空的原石。' },

  golden_cactus_fruit: { id: 'golden_cactus_fruit', name: '金沙仙人掌果', icon: '🌵', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['無垠沙漠'], use: '沙漠甜點與果汁。', description: '果皮沾著金沙的仙人掌果。' },
  sunlight_coconut: { id: 'sunlight_coconut', name: '陽光果汁椰', icon: '🥥', type: 'material', typeName: '食物素材', rarity: 'N', stars: 1, source: ['無垠沙漠'], use: '沙漠飲品與椰香甜點。', description: '裡面盛著陽光色果汁的椰子。' },
  oasis_dew: { id: 'oasis_dew', name: '沙洲露', icon: '💧', type: 'material', typeName: '食物素材', rarity: 'R', stars: 3, source: ['無垠沙漠'], use: '生長精華與清涼飲品。', description: '沙洲清晨凝出的珍貴露水。' },
  desert_oasis_dew: { id: 'desert_oasis_dew', name: '沙漠綠洲露', icon: '💧', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['無垠沙漠'], use: '萬物生長精華。', description: '綠洲中央最乾淨的一滴露水。' },
  crunchy_coin_fruit: { id: 'crunchy_coin_fruit', name: '脆脆金幣果', icon: '🪙', type: 'material', typeName: '食物素材', rarity: 'SR', stars: 5, source: ['無垠沙漠'], use: '高階金色甜點。', description: '咬下去會發出金幣聲的果實。' },
  oasis_melon_vine: { id: 'oasis_melon_vine', name: '綠洲蜜瓜蔓', icon: '🍈', type: 'material', typeName: '素材', rarity: 'N', stars: 1, source: ['無垠沙漠'], use: '沙漠甜點與植物配方。', description: '在綠洲邊緣攀爬的蜜瓜蔓。' },
  cactus_sugar: { id: 'cactus_sugar', name: '甜甜仙人掌糖', icon: '🍬', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['無垠沙漠'], use: '彩虹百匯與沙漠甜點。', description: '從仙人掌花蜜結成的甜糖。' },
  sandstone_chunk: { id: 'sandstone_chunk', name: '沙石碎塊', icon: '🪨', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['無垠沙漠'], use: '沙漠建材。', description: '被風磨圓的沙石碎塊。' },
  weathered_hard_branch: { id: 'weathered_hard_branch', name: '風化硬枝', icon: '🪵', type: 'rare_material', typeName: '結構素材', rarity: 'N', stars: 1, source: ['無垠沙漠'], use: '乾燥建材與支架。', description: '被沙風磨得堅硬的枯枝。' },
  golden_sand: { id: 'golden_sand', name: '黃金沙粒', icon: '✨', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['無垠沙漠'], use: '透光魔力磚。', description: '帶著金光的細沙。' },
  hardened_cactus_fiber: { id: 'hardened_cactus_fiber', name: '硬化仙人掌纖維', icon: '🧵', type: 'rare_material', typeName: '結構素材', rarity: 'R', stars: 3, source: ['無垠沙漠'], use: '耐熱仙人掌線與背包布料。', description: '曬乾後變得非常堅韌的仙人掌纖維。' },
  sun_fragment: { id: 'sun_fragment', name: '太陽碎片', icon: '☀️', type: 'rare_material', typeName: '結構素材', rarity: 'SR', stars: 5, source: ['無垠沙漠'], use: '幻影星空布與頂級裝備。', description: '像太陽剝落下來的一小塊光。' },

  neutralizer: { id: 'neutralizer', name: '溫和中和劑', icon: '🧪', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '魔法溶液與高階飲料基底。', description: '能完美融合不同屬性魔力的基礎溶劑，帶有淡淡奶香味。' },
  ice_fire_solution: { id: 'ice_fire_solution', name: '冰火調和液', icon: '🧪', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '冰火屬性煉金。', description: '同時具備極寒與極熱特性的神奇液體，裝在瓶子裡會不斷翻滾。' },
  growth_essence: { id: 'growth_essence', name: '萬物生長精華', icon: '🌱', type: 'refined_material', typeName: '三階煉成素材', tier: 3, rarity: 'SR', stars: 5, source: ['煉金室製作'], use: '傳說級溫室核心。', description: '滴一滴就能讓枯木逢春的頂級精華。' },
  frost_steel_ingot: { id: 'frost_steel_ingot', name: '霜鋼錠', icon: '🧊', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '設備升級與冷藏櫃。', description: '表面結著薄霜的堅硬鋼錠，散熱效果極佳。' },
  hot_mithril: { id: 'hot_mithril', name: '熾熱秘銀', icon: '🔥', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '高溫設備與星空琉璃金。', description: '內部隱隱透著紅光的秘銀，輕盈且耐高溫。' },
  star_glass_gold: { id: 'star_glass_gold', name: '星空琉璃金', icon: '🌌', type: 'refined_material', typeName: '三階煉成素材', tier: 3, rarity: 'SR', stars: 5, source: ['煉金室製作'], use: '王族級金屬與頂級設備。', description: '傳說中精靈王族使用的金屬，閃爍著星辰光芒。' },
  rotproof_wood: { id: 'rotproof_wood', name: '韌性防腐木', icon: '🪵', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '高級精靈家具與建材。', description: '塗上天然史萊姆膠的橡木，防水且不會腐壞。' },
  glowing_magic_brick: { id: 'glowing_magic_brick', name: '透光魔力磚', icon: '🧱', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '夜光建材與展示櫃。', description: '白天吸收陽光，晚上散發柔光的建材。' },
  world_tree_board: { id: 'world_tree_board', name: '世界樹庇護板', icon: '🌳', type: 'refined_material', typeName: '三階煉成素材', tier: 3, rarity: 'SR', stars: 5, source: ['煉金室製作'], use: '頂級精靈空間與家具。', description: '蘊含整座森林魔力的木板，能驅散負面情緒。' },
  stardust_warm_cloth: { id: 'stardust_warm_cloth', name: '星塵保溫布', icon: '🧶', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '沙發墊、窗簾與精靈小裝備。', description: '像雲朵一樣軟，會自動調節溫度。' },
  heatproof_cactus_thread: { id: 'heatproof_cactus_thread', name: '耐熱仙人掌線', icon: '🧵', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '耐熱布料與背包配方。', description: '丟進火裡也不會燒斷的強韌線材。' },
  phantom_starry_cloth: { id: 'phantom_starry_cloth', name: '幻影星空布', icon: '🌌', type: 'refined_material', typeName: '三階煉成素材', tier: 3, rarity: 'SR', stars: 5, source: ['煉金室製作'], use: '頂級精靈服飾。', description: '隨著光線變化出日出與星空圖案的傳說布料。' },
  magic_rope: { id: 'magic_rope', name: '魔法編織繩', icon: '🪢', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '背包擴充與家具綁束。', description: '由藤蔓與魔力纖維編成的結實繩索。' },
  strong_cactus_cloth: { id: 'strong_cactus_cloth', name: '強韌仙人掌布', icon: '🧵', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['煉金室製作'], use: '便攜採集藤編包。', description: '以硬化仙人掌纖維織成的耐磨布料。' },

  moon_latte: { id: 'moon_latte', name: '月光花瓣拿鐵', icon: '☕', type: 'drink', typeName: '飲品', rarity: 'SR', stars: 5, source: ['廚房製作', '委託獎勵'], use: '安定系飲品，可用於溫柔、祝福、月光主題委託。', description: '溫柔發光的奶泡像一層薄薄月色。' },
  star_berry_tart: { id: 'star_berry_tart', name: '星星莓奶油塔', icon: '🥧', type: 'sweet', typeName: '甜點', rarity: 'R', stars: 4, source: ['廚房製作', '委託獎勵'], use: '好運與活力主題委託常用甜點。', description: '星星莓鋪在奶油塔上，切開時會掉出金色糖屑。' },
  dream_cocoa: { id: 'dream_cocoa', name: '夜空碎片可可', icon: '🍫', type: 'drink', typeName: '飲品', rarity: 'SR', stars: 5, source: ['廚房製作', '委託獎勵'], use: '夢境、夜晚與安眠主題委託常用飲品。', description: '把夜空碎片融進可可裡，杯面浮出安靜星空。' },
  moon_dew: { id: 'moon_dew', name: '月光露珠', icon: '🌙', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'SR', stars: 5, source: ['煉金室製作'], use: '月光、祝福與安定系商品的二階素材。', description: '月光花瓣與星露水煉成的透明露珠。' },
  star_berry_syrup: { id: 'star_berry_syrup', name: '星莓糖漿', icon: '🍯', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 4, source: ['煉金室製作'], use: '甜點、飲品與好運主題商品的二階素材。', description: '星星莓熬成的金紅色糖漿。' },
  dream_essence: { id: 'dream_essence', name: '夢境精華', icon: '💤', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'SR', stars: 5, source: ['煉金室製作'], use: '夢境、夜晚與情緒主題商品的二階素材。', description: '夜空碎片在星露水中沉澱後留下的精華。' },
  pure_moon_essence: { id: 'pure_moon_essence', name: '純月精華', icon: '✨', type: 'refined_material', typeName: '三階煉成素材', tier: 3, rarity: 'SSR', stars: 5, source: ['煉金室製作'], use: '高階月光、祝福與夢境商品的核心材料。', description: '濃縮一整晚月色的高階精華。' },
  dawn_jam_berry_tart: { id: 'dawn_jam_berry_tart', name: '晨曦果醬莓果塔', icon: '🥧', type: 'sweet', typeName: '甜點', tier: 2, rarity: 'SR', stars: 5, source: ['廚房製作'], use: '高階森林甜點與委託。', description: '酥脆塔皮加上微溫果醬，咬下去像看見日出。' },
  mint_starry_soda: { id: 'mint_starry_soda', name: '薄荷星空氣泡飲', icon: '🥤', type: 'drink', typeName: '飲品', tier: 1, rarity: 'R', stars: 3, source: ['廚房製作'], use: '夏季飲品與清爽委託。', description: '喝下去會吐出帶有星光的小冰息。' },
  lava_pancake: { id: 'lava_pancake', name: '熔岩爆漿鬆餅', icon: '🥞', type: 'sweet', typeName: '甜點', tier: 2, rarity: 'SR', stars: 4, source: ['廚房製作'], use: '火山主題委託。', description: '切開會流出甜蜜岩漿，必須趁熱吃。' },
  rainbow_parfait: { id: 'rainbow_parfait', name: '終極大滿貫彩虹百匯', icon: '🍨', type: 'sweet', typeName: '頂級甜點', tier: 3, rarity: 'SSR', stars: 5, source: ['廚房製作'], use: '傳說級甜點委託。', description: '塞滿五顏六色甜點的終極夢幻冰品。' },
  warm_display_case: { id: 'warm_display_case', name: '初級保溫展示櫃', icon: '🗄️', type: 'product', typeName: '設備升級', rarity: 'SR', stars: 4, source: ['煉金室製作'], use: '設備升級。', description: '能讓蛋糕永遠保持剛出爐口感的神奇櫃子。' },
  portable_gather_bag: { id: 'portable_gather_bag', name: '便攜採集藤編包', icon: '🎒', type: 'product', typeName: '背包擴充道具', rarity: 'SR', stars: 4, source: ['煉金室製作'], use: '擴充店長背包容量。', description: '裡面的空間比看起來大得多。' },
  cleansing_incense_lamp: { id: 'cleansing_incense_lamp', name: '淨化薰香燈', icon: '🪔', type: 'product', typeName: '魔法家具', rarity: 'SSR', stars: 5, source: ['煉金室製作'], use: '魔法家具與高階委託。', description: '點燃後能驅散店內所有負面情緒。' },

  magic_fertilizer: { id: 'magic_fertilizer', name: '魔法肥料', icon: '🌱', type: 'event_material', typeName: '消耗道具', rarity: 'R', stars: 3, source: ['精靈商鋪'], use: '使用後恢復今日採集次數。', useButtonText: '使用肥料', useEffect: { type: 'resetGathering' }, description: '混入星露水與森林糖粉的魔法肥料。撒在採集地點後，植物會重新打起精神，讓今天的採集次數恢復。' },
};

export const itemSources = Object.fromEntries(Object.keys(items).map((itemId) => [itemId, { type: 'route', id: 'collection' }]));

Object.assign(itemSources, {
  moon_petals: { type: 'scene', id: 'greenhouse' },
  star_berry: { type: 'scene', id: 'backyard' },
  night_sky_fragment: { type: 'route', id: 'gacha' },
  forest_cookie: { type: 'scene', id: 'backyard' },
  stardew_water: { type: 'scene', id: 'backyard' },
  moon_latte: { type: 'station', id: 'kitchen' },
  star_berry_tart: { type: 'station', id: 'kitchen' },
  dream_cocoa: { type: 'station', id: 'kitchen' },
  moon_dew: { type: 'station', id: 'alchemy' },
  star_berry_syrup: { type: 'station', id: 'alchemy' },
  dream_essence: { type: 'station', id: 'alchemy' },
  pure_moon_essence: { type: 'station', id: 'alchemy' },
  dawn_jam_berry_tart: { type: 'station', id: 'kitchen' },
  mint_starry_soda: { type: 'station', id: 'kitchen' },
  lava_pancake: { type: 'station', id: 'kitchen' },
  rainbow_parfait: { type: 'station', id: 'kitchen' },
  warm_display_case: { type: 'station', id: 'alchemy' },
  portable_gather_bag: { type: 'station', id: 'alchemy' },
  cleansing_incense_lamp: { type: 'station', id: 'alchemy' },
  magic_fertilizer: { type: 'route', id: 'shop' },
});
