export const fairies = {
  moon_petals_fairy: {
    id: 'moon_petals_fairy', name: '月光花瓣精靈', icon: '🧚‍♀️', rarity: 'SSR', source: ['祈願'], quote: '今晚的月色，由我替你保管。', description: '守著滿月花園的小精靈，會把柔和的祝福藏進飲品泡沫裡。', story: '她原本住在滿月才會開花的溫室角落，喜歡把安靜的月光折成小信紙。', favoriteSweets: ['moon_latte', 'dream_cocoa'], passiveBuff: { type: 'gatherQtyBonus', target: 'greenhouse', value: 0.2, label: '溫室採集量 +20%' }, dialogues: { low: ['要不要先把花瓣泡得更溫柔一點？', '我會在月光最亮的地方等你。'], mid: ['今天的月光很適合做拿鐵。', '你靠近時，花瓣會自己發光呢。'], high: ['這間咖啡屋的月色，已經有家的味道了。'] },
  },
  night_sky_fairy: {
    id: 'night_sky_fairy', name: '夜空碎片精靈', icon: '🌠', rarity: 'SSR', source: ['祈願'], quote: '迷路的星星，也會找到回家的路。', description: '從夜空裂縫裡醒來的精靈，擅長保存夢境與微弱的光。', story: '她曾是一片落在咖啡杯裡的星空碎片，醒來後就開始替失眠的客人守夢。', favoriteSweets: ['dream_cocoa'], passiveBuff: { type: 'rareDropBonus', target: 'all', value: 0.05, label: '稀有事件機率 +5%' }, dialogues: { low: ['噓，夢快醒了。', '夜晚不是黑的，是很多小光躲起來。'], mid: ['我把一小片安靜星空留給你。', '如果睡不著，就喝一口可可吧。'], high: ['迷路的夢，也願意回到這裡。'] },
  },
  honey_lantern_fairy: {
    id: 'honey_lantern_fairy', name: '蜂蜜燈籠精靈', icon: '🏮', rarity: 'SSR', source: ['祈願'], quote: '我會替你照亮這間小店。', description: '提著蜂蜜色小燈籠，會在傍晚替咖啡屋點亮暖光。', story: '她會把傍晚最後一點蜂蜜色陽光收進燈籠，讓客人回家時不會迷路。', favoriteSweets: ['forest_cookie', 'star_berry_tart'], passiveBuff: { type: 'leafCoinBonus', target: 'commission', value: 0.1, label: '委託葉幣 +10%' }, dialogues: { low: ['燈還亮著，慢慢來就好。', '今天也要把門口擦得亮晶晶。'], mid: ['我替你留了一盞小燈。', '蜂蜜色的光最適合傍晚的咖啡屋。'], high: ['只要燈還亮著，你就不是一個人經營。'] },
  },
  star_berry_fairy: {
    id: 'star_berry_fairy', name: '星星莓精靈', icon: '🍓', rarity: 'SSR', source: ['祈願'], quote: '甜甜的好運，已經送到你手上囉。', description: '喜歡偷吃莓果塔的小精靈，走過的地方會留下金色糖屑。', story: '她總是假裝自己沒有偷吃莓果塔，但每次嘴邊都沾著星星莓果醬。', favoriteSweets: ['star_berry_tart', 'forest_cookie'], passiveBuff: { type: 'gatherQtyBonus', target: 'backyard', value: 0.2, label: '後山採集量 +20%' }, dialogues: { low: ['星星莓今天也很甜喔。', '欸？不是我偷吃的啦。'], mid: ['如果你給我莓果塔，我會把好運分你一半。', '金色糖屑是幸運的證明！'], high: ['跟你一起顧店，比莓果塔還甜。'] },
  },
  cloud_milk_fairy: { id: 'cloud_milk_fairy', name: '雲朵牛奶精靈', icon: '☁️', rarity: 'SR', source: ['祈願'], quote: '今天也要把奶泡打得軟綿綿。', description: '住在奶泡裡的小精靈，說話像棉花糖一樣慢。', story: '她會在清晨把雲朵折進牛奶瓶裡。', favoriteSweets: ['moon_latte', 'mint_starry_soda'], passiveBuff: { type: 'craftBonus', target: 'drink', value: 0.05, label: '飲品製作加成 +5%' }, dialogues: { low: ['不要急，泡泡會慢慢長大。'], mid: ['我幫你把杯口變得更柔軟。'], high: ['這杯奶泡有家的味道。'] } },
  silver_leaf_fairy: { id: 'silver_leaf_fairy', name: '銀葉茶精靈', icon: '🍵', rarity: 'SR', source: ['祈願'], quote: '請把吵雜留在杯外。', description: '安靜端正的茶葉精靈，喜歡整理茶櫃。', story: '她從一片銀色葉脈中醒來，第一件事是擦亮茶匙。', favoriteSweets: ['moon_latte', 'dream_cocoa'], passiveBuff: { type: 'commissionBonus', target: 'tea', value: 0.05, label: '茶會委託加成 +5%' }, dialogues: { low: ['茶要等，心也要等。'], mid: ['這壺茶已經醒好了。'], high: ['你泡的茶越來越像月光。'] } },
  bell_flower_fairy: { id: 'bell_flower_fairy', name: '鈴蘭花精靈', icon: '🔔', rarity: 'SR', source: ['祈願'], quote: '叮鈴，今天的魔法醒了。', description: '走路會發出細小鈴聲的花精靈。', story: '她負責叫醒睡過頭的香氣與祝福。', favoriteSweets: ['star_berry_tart'], passiveBuff: { type: 'rareDropBonus', target: 'greenhouse', value: 0.03, label: '溫室稀有事件 +3%' }, dialogues: { low: ['小聲一點，花正在睡。'], mid: ['我聽見香氣醒來了。'], high: ['只要你叫我，我就會叮鈴一聲出現。'] } },
  comet_peel_fairy: { id: 'comet_peel_fairy', name: '彗星果皮精靈', icon: '🍊', rarity: 'SR', source: ['祈願'], quote: '我不是遲到，我只是繞了一圈銀河！', description: '總是帶著橙色尾光衝進店裡的活潑精靈。', story: '她從彗星果皮的香氣裡誕生，最喜歡閃亮的飲品。', favoriteSweets: ['mint_starry_soda'], passiveBuff: { type: 'gatherQtyBonus', target: 'all', value: 0.05, label: '全地點採集量 +5%' }, dialogues: { low: ['咻——我來了！'], mid: ['今天要不要做一杯會發光的蘇打？'], high: ['我會把好消息用最快速度送來。'] } },
  mint_fairy: { id: 'mint_fairy', name: '露水薄荷精靈', icon: '🌿', rarity: 'R', source: ['祈願'], quote: '深呼吸，涼涼的就不怕了。', description: '負責讓廚房保持清爽的小精靈。', story: '她住在溫室最涼的角落，會替緊張的客人倒水。', favoriteSweets: ['mint_starry_soda'], passiveBuff: { type: 'craftBonus', target: 'drink', value: 0.03, label: '飲品製作加成 +3%' }, dialogues: { low: ['要喝水嗎？'], mid: ['薄荷已經洗乾淨了。'], high: ['你累的時候，我會替你吹一點風。'] } },
  acorn_fairy: { id: 'acorn_fairy', name: '小橡果精靈', icon: '🌰', rarity: 'R', source: ['祈願'], quote: '這顆不是偷藏的，是備用！', description: '喜歡把材料塞進口袋的小小森林精靈。', story: '她的圍裙口袋比看起來深很多。', favoriteSweets: ['forest_cookie', 'star_berry_tart'], passiveBuff: { type: 'gatherQtyBonus', target: 'backyard', value: 0.08, label: '後山採集量 +8%' }, dialogues: { low: ['我有存貨喔。'], mid: ['橡果可以做焦糖嗎？'], high: ['我的秘密倉庫也可以借你。'] } },
  cocoa_fairy: { id: 'cocoa_fairy', name: '絲絨可可精靈', icon: '🍫', rarity: 'R', source: ['祈願'], quote: '苦一點也沒關係，最後會變甜。', description: '溫柔沉穩的可可精靈，擅長安撫失眠客人。', story: '她從一杯熱可可的霧氣裡慢慢坐起來。', favoriteSweets: ['dream_cocoa'], passiveBuff: { type: 'commissionBonus', target: 'night', value: 0.04, label: '夜晚委託加成 +4%' }, dialogues: { low: ['小心燙。'], mid: ['這杯可可會陪你到睡著。'], high: ['苦味也可以被好好保存。'] } },
  sun_sugar_fairy: { id: 'sun_sugar_fairy', name: '日光砂糖精靈', icon: '☀️', rarity: 'R', source: ['祈願'], quote: '今天也要亮亮甜甜！', description: '像小太陽一樣的砂糖精靈。', story: '她會把晴天磨成細細砂糖。', favoriteSweets: ['lava_pancake', 'star_berry_tart'], passiveBuff: { type: 'leafCoinBonus', target: 'commission', value: 0.04, label: '委託葉幣 +4%' }, dialogues: { low: ['早安！'], mid: ['我把甜味曬好了。'], high: ['你笑起來比砂糖還亮。'] } },
  crystal_salt_fairy: { id: 'crystal_salt_fairy', name: '晶鹽精靈', icon: '🧂', rarity: 'R', source: ['祈願'], quote: '甜味也需要一點安定。', description: '負責校正味道與魔力反應的小精靈。', story: '她會用鹽晶排成小小魔法陣。', favoriteSweets: ['star_berry_tart'], passiveBuff: { type: 'craftBonus', target: 'all', value: 0.02, label: '全製作加成 +2%' }, dialogues: { low: ['再一點點就好。'], mid: ['味道平衡了。'], high: ['我會幫你守住不失敗的那一點。'] } },
  moon_jam_fairy: { id: 'moon_jam_fairy', name: '月光果醬精靈', icon: '🫙', rarity: 'SR', source: ['祈願'], quote: '把月光熬久一點，就會變成甜的。', description: '黏在果醬瓶邊的小精靈，喜歡慢慢攪拌。', story: '她把夜晚的安靜煮成果醬，封在玻璃瓶裡。', favoriteSweets: ['dawn_jam_berry_tart', 'moon_latte'], passiveBuff: { type: 'craftBonus', target: 'sweet', value: 0.05, label: '甜點製作加成 +5%' }, dialogues: { low: ['還不能吃，要再熬一下。'], mid: ['果醬亮起來了。'], high: ['我留了最甜的一匙給你。'] } },
  picnic_basket_fairy: { id: 'picnic_basket_fairy', name: '野餐籃精靈', icon: '🧺', rarity: 'SR', source: ['祈願'], quote: '出門也要帶著咖啡屋的香氣。', description: '喜歡把甜點排得整整齊齊的野餐精靈。', story: '她會替客人準備不會壓壞的點心籃。', favoriteSweets: ['dawn_jam_berry_tart', 'forest_cookie'], passiveBuff: { type: 'commissionBonus', target: 'product', value: 0.05, label: '產品委託加成 +5%' }, dialogues: { low: ['餐巾折好了。'], mid: ['這個籃子剛好放得下。'], high: ['下次我們也一起去野餐吧。'] } },
};
