export const recipes = {
  recipe_moon_latte: {
    id: 'recipe_moon_latte',
    name: '月光花瓣拿鐵',
    station: 'kitchen',
    category: 'drink',
    cost: { moon_petals: 1, stardew_water: 1 },
    output: { itemId: 'moon_latte', qty: 1 },
    description: '把月光花瓣泡進星露水裡，再加入柔和奶泡，做成安定系飲品。',
  },
  recipe_star_berry_tart: {
    id: 'recipe_star_berry_tart',
    name: '星星莓奶油塔',
    station: 'kitchen',
    category: 'sweet',
    cost: { star_berry: 2, forest_cookie: 1 },
    output: { itemId: 'star_berry_tart', qty: 1 },
    description: '把森林餅乾壓成塔皮，鋪上星星莓與奶油，做成會掉金色糖屑的小塔。',
  },
  recipe_dream_cocoa: {
    id: 'recipe_dream_cocoa',
    name: '夜空碎片可可',
    station: 'kitchen',
    category: 'drink',
    cost: { night_sky_fragment: 1, stardew_water: 1 },
    output: { itemId: 'dream_cocoa', qty: 1 },
    description: '把夜空碎片溶進熱可可，讓杯面浮出一片安靜的星空。',
  },
  recipe_moon_dew: {
    id: 'recipe_moon_dew',
    name: '月光露珠',
    station: 'alchemy',
    category: 'refined_material',
    cost: { moon_petals: 1, stardew_water: 1 },
    output: { itemId: 'moon_dew', qty: 1 },
    description: '把月光花瓣與星露水低溫煉成透明露珠，是月光系商品的基礎素材。',
  },
  recipe_star_berry_syrup: {
    id: 'recipe_star_berry_syrup',
    name: '星莓糖漿',
    station: 'alchemy',
    category: 'refined_material',
    cost: { star_berry: 2, stardew_water: 1 },
    output: { itemId: 'star_berry_syrup', qty: 1 },
    description: '把星星莓熬成帶有星屑感的糖漿，是甜點與飲品的常用煉成素材。',
  },
  recipe_dream_essence: {
    id: 'recipe_dream_essence',
    name: '夢境精華',
    station: 'alchemy',
    category: 'refined_material',
    cost: { night_sky_fragment: 1, stardew_water: 1 },
    output: { itemId: 'dream_essence', qty: 1 },
    description: '讓夜空碎片在星露水中沉澱，提取出安靜的夢境精華。',
  },
  recipe_pure_moon_essence: {
    id: 'recipe_pure_moon_essence',
    name: '純月精華',
    station: 'alchemy',
    category: 'refined_material',
    cost: { moon_dew: 1, night_sky_fragment: 1 },
    output: { itemId: 'pure_moon_essence', qty: 1 },
    description: '將月光露珠與夜空碎片再次穩定化，煉成高階月光與夢境商品使用的三階素材。',
  },
};
