export const items = {
  moon_petals: {
    id: 'moon_petals',
    name: '月光花瓣',
    icon: '🌙',
    type: 'material',
    typeName: '素材',
    rarity: 'SR',
    stars: 5,
    source: ['簽到', '祈願', '溫室'],
    use: '提升藥水純度、製作月光系飲品。',
    description: '只在滿月之夜綻放的花朵所掉落的花瓣，吸收了月光後會微微發亮。常被用於提升藥水的純度與安定性，也象徵溫柔與祝福。',
  },
  star_berry: {
    id: 'star_berry',
    name: '星星莓',
    icon: '🍓',
    type: 'material',
    typeName: '素材',
    rarity: 'R',
    stars: 4,
    source: ['簽到', '祈願', '後山'],
    use: '加入甜點或飲品，增加好運與活力。',
    description: '生長在魔力濃厚地區的莓果，果皮上自然形成金箔斑點。味道甜中帶微酸，常被加入甜點或飲品中，象徵好運與活力。',
  },
  night_sky_fragment: {
    id: 'night_sky_fragment',
    name: '夜空碎片',
    icon: '🌌',
    type: 'material',
    typeName: '素材',
    rarity: 'SR',
    stars: 5,
    source: ['祈願'],
    use: '用於夜晚、夢境或情緒相關的魔法商品；之後可作為煉金高階材料。',
    description: '夜晚天空中掉落的碎片，彷彿封存了一小段星空。常用於與夜晚、夢境或情緒相關的魔法。',
  },
  forest_cookie: {
    id: 'forest_cookie',
    name: '森林餅乾',
    icon: '🍪',
    type: 'sweet',
    typeName: '甜點',
    rarity: 'R',
    stars: 2,
    source: ['祈願', '後山'],
    use: '普通委託常見的小甜點，也能作為廚房產品的基底。',
    description: '烤成葉片形狀的小餅乾，帶著淡淡蜂蜜與木質香。',
  },
  stardew_water: {
    id: 'stardew_water',
    name: '星露水',
    icon: '💧',
    type: 'material',
    typeName: '素材',
    rarity: 'R',
    stars: 3,
    source: ['祈願', '簽到', '後山', '溫室'],
    use: '澆灌魔法植物，或作為飲品與煉成的基底。',
    description: '清晨凝在花瓣上的露水，映著細小星光。',
  },
  moon_latte: {
    id: 'moon_latte',
    name: '月光花瓣拿鐵',
    icon: '☕',
    type: 'drink',
    typeName: '飲品',
    rarity: 'SR',
    stars: 5,
    source: ['廚房製作', '委託獎勵'],
    use: '安定系飲品，可用於溫柔、祝福、月光主題委託。',
    description: '溫柔發光的奶泡像一層薄薄月色，喝下後心情會慢慢安定。',
  },
  star_berry_tart: {
    id: 'star_berry_tart',
    name: '星星莓奶油塔',
    icon: '🥧',
    type: 'sweet',
    typeName: '甜點',
    rarity: 'R',
    stars: 4,
    source: ['廚房製作', '委託獎勵'],
    use: '好運與活力主題委託常用甜點。',
    description: '星星莓鋪在奶油塔上，切開時會掉出一點金色糖屑。',
  },
  dream_cocoa: {
    id: 'dream_cocoa',
    name: '夜空碎片可可',
    icon: '🍫',
    type: 'drink',
    typeName: '飲品',
    rarity: 'SR',
    stars: 5,
    source: ['廚房製作', '委託獎勵'],
    use: '夢境、夜晚與安眠主題委託常用飲品。',
    description: '把夜空碎片融進可可裡，杯面會浮出一小片安靜星空。',
  },
  moon_dew: {
    id: 'moon_dew',
    name: '月光露珠',
    icon: '🌙',
    type: 'refined_material',
    typeName: '煉成素材',
    tier: 2,
    rarity: 'SR',
    stars: 5,
    source: ['煉金室製作'],
    use: '月光、祝福與安定系商品的二階素材。',
    description: '把月光花瓣與星露水慢慢煉成的透明露珠，會在瓶底映出一圈柔光。',
  },
  star_berry_syrup: {
    id: 'star_berry_syrup',
    name: '星莓糖漿',
    icon: '🍯',
    type: 'refined_material',
    typeName: '煉成素材',
    tier: 2,
    rarity: 'R',
    stars: 4,
    source: ['煉金室製作'],
    use: '甜點、飲品與好運主題商品的二階素材。',
    description: '星星莓熬成的金紅色糖漿，搖晃時會出現細小星屑。',
  },
  dream_essence: {
    id: 'dream_essence',
    name: '夢境精華',
    icon: '💤',
    type: 'refined_material',
    typeName: '煉成素材',
    tier: 2,
    rarity: 'SR',
    stars: 5,
    source: ['煉金室製作'],
    use: '夢境、夜晚與情緒主題商品的二階素材。',
    description: '夜空碎片在星露水中沉澱後留下的精華，像一小團安靜的夢。',
  },
  pure_moon_essence: {
    id: 'pure_moon_essence',
    name: '純月精華',
    icon: '✨',
    type: 'refined_material',
    typeName: '三階煉成素材',
    tier: 3,
    rarity: 'SSR',
    stars: 5,
    source: ['煉金室製作'],
    use: '高階月光、祝福與夢境商品的核心材料。',
    description: '將月光露珠與夜空碎片再次穩定化後形成的精華，像把一整晚的月色濃縮成一滴光。',
  },
  magic_fertilizer: {
    id: 'magic_fertilizer',
    name: '魔法肥料',
    icon: '🌱',
    type: 'event_material',
    typeName: '消耗道具',
    rarity: 'R',
    stars: 3,
    source: ['精靈商鋪'],
    use: '使用後恢復今日採集次數。',
    useButtonText: '使用肥料',
    useEffect: { type: 'resetGathering' },
    description: '混入星露水與森林糖粉的魔法肥料。撒在採集地點後，植物會重新打起精神，讓今天的採集次數恢復。',
  },
  honey_drop: { id: 'honey_drop', name: '蜂蜜露珠', icon: '🍯', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['後山'], use: '製作甜點與溫暖系飲品。', description: '掛在樹葉尖端的蜂蜜色露珠，帶著木頭與陽光的香氣。' },
  silver_leaf: { id: 'silver_leaf', name: '銀葉片', icon: '🍃', type: 'material', typeName: '素材', rarity: 'SR', stars: 4, source: ['後山'], use: '高階裝飾、藥水穩定與精靈禮物。', description: '葉脈泛著銀光的薄葉，揉碎後會像星屑一樣散開。' },
  sun_sugar: { id: 'sun_sugar', name: '日光砂糖', icon: '☀️', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['溫室'], use: '提高甜點亮度與香氣。', description: '在晴天凝成的小顆粒砂糖，摸起來微微溫熱。' },
  cloud_milk: { id: 'cloud_milk', name: '雲朵牛奶', icon: '🥛', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['祈願'], use: '飲品基底，可讓奶泡更輕盈。', description: '像小雲一樣蓬鬆的牛奶，倒進杯子時會浮出柔白泡沫。' },
  crystal_salt: { id: 'crystal_salt', name: '晶鹽', icon: '🧂', type: 'material', typeName: '素材', rarity: 'N', stars: 2, source: ['後山'], use: '平衡甜味與魔力反應。', description: '透明的小鹽晶，能把過度活躍的魔力稍微安定下來。' },
  velvet_cocoa: { id: 'velvet_cocoa', name: '絲絨可可粉', icon: '🍫', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['精靈商鋪'], use: '可可與巧克力甜點基底。', description: '細緻如天鵝絨的可可粉，帶著一點夜晚香氣。' },
  tiny_acorn: { id: 'tiny_acorn', name: '小橡果', icon: '🌰', type: 'material', typeName: '素材', rarity: 'N', stars: 2, source: ['後山'], use: '森林系餅乾、堅果糖與精靈禮物。', description: '森林松鼠常常藏起來的小橡果，敲開後有淡淡甜香。' },
  dew_mint: { id: 'dew_mint', name: '露水薄荷', icon: '🌿', type: 'material', typeName: '素材', rarity: 'R', stars: 3, source: ['溫室'], use: '清爽飲品與降溫魔法。', description: '葉面永遠覆著一層清晨露水的薄荷。' },
  lantern_honey: { id: 'lantern_honey', name: '燈籠蜂蜜', icon: '🏮', type: 'material', typeName: '素材', rarity: 'SR', stars: 4, source: ['祈願'], use: '暖光系甜點與精靈好感禮。', description: '裝在小燈籠瓶裡的蜂蜜，夜晚會自己發出柔光。' },
  bell_flower: { id: 'bell_flower', name: '鈴蘭花', icon: '🔔', type: 'material', typeName: '素材', rarity: 'SR', stars: 4, source: ['溫室'], use: '香氛、藥水與祝福甜點。', description: '花朵搖晃時會發出很輕的鈴聲，據說能叫醒睡著的魔法。' },
  comet_peel: { id: 'comet_peel', name: '彗星果皮', icon: '🍊', type: 'rare_material', typeName: '稀有素材', rarity: 'SR', stars: 4, source: ['祈願'], use: '星空系飲品與特殊香氣。', description: '彗星果削下的果皮，邊緣閃著拖尾般的光。' },
  fairy_flour: { id: 'fairy_flour', name: '精靈麵粉', icon: '🌾', type: 'material', typeName: '素材', rarity: 'N', stars: 2, source: ['精靈商鋪'], use: '所有烘焙甜點的通用基底。', description: '磨得很細的魔法小麥粉，揉麵時會自己變得蓬鬆。' },
  moon_jam: { id: 'moon_jam', name: '月光果醬', icon: '🫙', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'SR', stars: 4, source: ['煉金室製作'], use: '月光甜點、果醬塔與禮盒。', description: '把月光花瓣和蜂蜜露珠熬成的半透明果醬。' },
  honey_cream: { id: 'honey_cream', name: '蜂蜜奶油', icon: '🧈', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['廚房製作'], use: '奶油塔、鬆餅與餅乾內餡。', description: '柔滑的金色奶油，抹開時會出現細細光紋。' },
  mint_syrup: { id: 'mint_syrup', name: '薄荷糖漿', icon: '🍃', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['廚房製作'], use: '清爽飲品、夏季限定甜點。', description: '露水薄荷熬成的透明糖漿，搖晃時像小河一樣流動。' },
  bell_flower_extract: { id: 'bell_flower_extract', name: '鈴花萃取液', icon: '🧪', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'SR', stars: 4, source: ['煉金室製作'], use: '香氛、祝福藥水與特殊委託。', description: '從鈴蘭花中提取出的清亮液體，靠近耳邊會聽見細小鈴聲。' },
  comet_zest: { id: 'comet_zest', name: '彗星香屑', icon: '✨', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'SR', stars: 4, source: ['煉金室製作'], use: '點綴星空甜點與高階飲品。', description: '彗星果皮刨出的香屑，會在奶泡上留下尾光。' },
  forest_caramel: { id: 'forest_caramel', name: '森林焦糖', icon: '🍮', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'R', stars: 3, source: ['廚房製作'], use: '焦糖布丁、拿鐵與暖系甜點。', description: '以小橡果和日光砂糖熬成的焦糖，帶著森林烤香。' },
  silver_tea_base: { id: 'silver_tea_base', name: '銀葉茶底', icon: '🍵', type: 'refined_material', typeName: '煉成素材', tier: 2, rarity: 'SR', stars: 4, source: ['廚房製作'], use: '高雅茶飲與冷泡飲品。', description: '銀葉片泡出的茶底，茶面會泛出淡淡月白色。' },
  moon_jam_scone: { id: 'moon_jam_scone', name: '月光果醬司康', icon: '🥐', type: 'sweet', typeName: '甜點', rarity: 'SR', stars: 4, source: ['廚房製作'], use: '下午茶與月光主題委託。', description: '夾著月光果醬的司康，掰開時會露出柔亮果醬。' },
  honey_pancake: { id: 'honey_pancake', name: '蜂蜜鬆餅', icon: '🥞', type: 'sweet', typeName: '甜點', rarity: 'R', stars: 3, source: ['廚房製作'], use: '森林客人喜歡的早餐甜點。', description: '淋上燈籠蜂蜜的鬆餅，邊緣烤得蓬鬆金黃。' },
  mint_cloud_soda: { id: 'mint_cloud_soda', name: '薄荷雲朵蘇打', icon: '🥤', type: 'drink', typeName: '飲品', rarity: 'R', stars: 3, source: ['廚房製作'], use: '清涼、夏日、活力主題委託。', description: '薄荷糖漿和雲朵牛奶調成的氣泡飲，杯口浮著白色小雲。' },
  silver_leaf_tea: { id: 'silver_leaf_tea', name: '銀葉冷泡茶', icon: '🍵', type: 'drink', typeName: '飲品', rarity: 'SR', stars: 4, source: ['廚房製作'], use: '安靜、高雅與夜晚委託。', description: '銀葉茶底冷泡而成，喝起來像清晨森林裡的一口風。' },
  comet_orange_soda: { id: 'comet_orange_soda', name: '彗星橙光蘇打', icon: '🍹', type: 'drink', typeName: '飲品', rarity: 'SR', stars: 4, source: ['廚房製作'], use: '節慶、星空與驚喜委託。', description: '杯中有橙色尾光旋轉，像一顆小彗星落進氣泡裡。' },
  forest_caramel_pudding: { id: 'forest_caramel_pudding', name: '森林焦糖布丁', icon: '🍮', type: 'sweet', typeName: '甜點', rarity: 'R', stars: 3, source: ['廚房製作'], use: '溫暖系委託與精靈禮物。', description: '小橡果焦糖淋在布丁上，入口有淡淡木質香。' },
  bell_flower_parfait: { id: 'bell_flower_parfait', name: '鈴花香草杯', icon: '🍨', type: 'sweet', typeName: '甜點', rarity: 'SR', stars: 4, source: ['廚房製作'], use: '祝福、香氛與高雅委託。', description: '香草奶霜間藏著鈴花萃取液，湯匙碰到杯壁會叮一聲。' },
  moonlight_gift_box: { id: 'moonlight_gift_box', name: '月光禮盒', icon: '🎁', type: 'product', typeName: '產品', rarity: 'SR', stars: 5, source: ['廚房製作'], use: '高階月光主題委託與精靈禮物。', description: '裝著月光果醬司康與銀葉茶包的小禮盒，盒蓋內側映著月色。' },
  forest_picnic_set: { id: 'forest_picnic_set', name: '森林野餐組', icon: '🧺', type: 'product', typeName: '產品', rarity: 'R', stars: 4, source: ['廚房製作'], use: '森林客人、郊遊與社團委託。', description: '蜂蜜鬆餅、森林焦糖布丁和小茶包組成的野餐籃。' },
  starlit_sleep_set: { id: 'starlit_sleep_set', name: '星夜安眠組', icon: '🌠', type: 'product', typeName: '產品', rarity: 'SR', stars: 5, source: ['廚房製作'], use: '安眠、夢境與夜晚客人委託。', description: '夜空可可、夢境精華與小餅乾組成的睡前禮包。' },
  sunny_brunch_set: { id: 'sunny_brunch_set', name: '日光早午餐組', icon: '🍽️', type: 'product', typeName: '產品', rarity: 'R', stars: 4, source: ['廚房製作'], use: '早晨、活力與日光主題委託。', description: '日光砂糖烤出的甜點組合，適合一早送到客人手上。' },
  silver_moon_tea_set: { id: 'silver_moon_tea_set', name: '銀月茶會組', icon: '🫖', type: 'product', typeName: '產品', rarity: 'SR', stars: 5, source: ['廚房製作'], use: '茶會、高雅與月光活動委託。', description: '銀葉冷泡茶搭配月光甜點，茶杯邊緣像鍍了銀。' },
  tiny_thank_you_card: { id: 'tiny_thank_you_card', name: '小小感謝卡', icon: '💌', type: 'event_material', typeName: '活動素材', rarity: 'N', stars: 1, source: ['委託獎勵'], use: '活動兌換與紀念收藏。', description: '客人留下的小卡片，上面寫著歪歪扭扭但很真心的謝謝。' },
  lucky_clover: { id: 'lucky_clover', name: '幸運四葉草', icon: '🍀', type: 'event_material', typeName: '消耗道具', rarity: 'R', stars: 3, source: ['精靈商鋪'], use: '未來可用於提升下一次採集幸運。', description: '葉片上帶著金邊的四葉草，拿著它時感覺今天會遇到好事。' },
  moonlight_incense: { id: 'moonlight_incense', name: '月光香氛', icon: '🕯️', type: 'event_material', typeName: '消耗道具', rarity: 'SR', stars: 4, source: ['精靈商鋪'], use: '未來可用於提升精靈好感。', description: '點燃後會飄出很淡的月白香氣，精靈們會變得比較放鬆。' },
  star_sand_bottle: { id: 'star_sand_bottle', name: '星砂瓶', icon: '⌛', type: 'event_material', typeName: '消耗道具', rarity: 'SR', stars: 4, source: ['精靈商鋪'], use: '未來可用於祈願或活動加成。', description: '瓶中裝著一小撮會發光的星砂，倒過來時像迷你銀河。' },
};

export const itemSources = {
  moon_petals: { type: 'scene', id: 'greenhouse' },
  star_berry: { type: 'scene', id: 'backyard' },
  night_sky_fragment: { type: 'route', id: 'gacha' },
  forest_cookie: { type: 'scene', id: 'backyard' },
  stardew_water: { type: 'scene', id: 'backyard' },
  moon_latte: { type: 'station', id: 'kitchen' },
  star_berry_tart: { type: 'station', id: 'kitchen' },
  dream_cocoa: { type: 'station', id: 'kitchen' },
  moon_dew: { type: 'station', id: 'alchemy' },
  star_berry_syrup: { type: 'station', id: 'alchemy' },
  dream_essence: { type: 'station', id: 'alchemy' },
  pure_moon_essence: { type: 'station', id: 'alchemy' },
  magic_fertilizer: { type: 'route', id: 'shop' },
  honey_drop: { type: 'scene', id: 'backyard' },
  silver_leaf: { type: 'scene', id: 'backyard' },
  sun_sugar: { type: 'scene', id: 'greenhouse' },
  cloud_milk: { type: 'route', id: 'gacha' },
  crystal_salt: { type: 'scene', id: 'backyard' },
  velvet_cocoa: { type: 'route', id: 'shop' },
  tiny_acorn: { type: 'scene', id: 'backyard' },
  dew_mint: { type: 'scene', id: 'greenhouse' },
  lantern_honey: { type: 'route', id: 'gacha' },
  bell_flower: { type: 'scene', id: 'greenhouse' },
  comet_peel: { type: 'route', id: 'gacha' },
  fairy_flour: { type: 'route', id: 'shop' },
  moon_jam: { type: 'station', id: 'alchemy' },
  honey_cream: { type: 'station', id: 'kitchen' },
  mint_syrup: { type: 'station', id: 'kitchen' },
  bell_flower_extract: { type: 'station', id: 'alchemy' },
  comet_zest: { type: 'station', id: 'alchemy' },
  forest_caramel: { type: 'station', id: 'kitchen' },
  silver_tea_base: { type: 'station', id: 'kitchen' },
  moon_jam_scone: { type: 'station', id: 'kitchen' },
  honey_pancake: { type: 'station', id: 'kitchen' },
  mint_cloud_soda: { type: 'station', id: 'kitchen' },
  silver_leaf_tea: { type: 'station', id: 'kitchen' },
  comet_orange_soda: { type: 'station', id: 'kitchen' },
  forest_caramel_pudding: { type: 'station', id: 'kitchen' },
  bell_flower_parfait: { type: 'station', id: 'kitchen' },
  moonlight_gift_box: { type: 'station', id: 'kitchen' },
  forest_picnic_set: { type: 'station', id: 'kitchen' },
  starlit_sleep_set: { type: 'station', id: 'kitchen' },
  sunny_brunch_set: { type: 'station', id: 'kitchen' },
  silver_moon_tea_set: { type: 'station', id: 'kitchen' },
  tiny_thank_you_card: { type: 'route', id: 'commissions' },
  lucky_clover: { type: 'route', id: 'shop' },
  moonlight_incense: { type: 'route', id: 'shop' },
  star_sand_bottle: { type: 'route', id: 'shop' },
};
