export const items = {
  moon_petals: {
    id: 'moon_petals',
    name: '月光花瓣',
    icon: '🌙',
    type: 'material',
    typeName: '素材',
    rarity: 'SR',
    stars: 5,
    source: ['簽到', '祈願', '溫室'],
    use: '提升藥水純度、製作月光系飲品。',
    description: '只在滿月之夜綻放的花朵所掉落的花瓣，吸收了月光後會微微發亮。常被用於提升藥水的純度與安定性，也象徵溫柔與祝福。',
  },
  star_berry: {
    id: 'star_berry',
    name: '星星莓',
    icon: '🍓',
    type: 'material',
    typeName: '素材',
    rarity: 'R',
    stars: 4,
    source: ['簽到', '祈願', '後山'],
    use: '加入甜點或飲品，增加好運與活力。',
    description: '生長在魔力濃厚地區的莓果，果皮上自然形成金箔斑點。味道甜中帶微酸，常被加入甜點或飲品中，象徵好運與活力。',
  },
  night_sky_fragment: {
    id: 'night_sky_fragment',
    name: '夜空碎片',
    icon: '🌌',
    type: 'material',
    typeName: '素材',
    rarity: 'SR',
    stars: 5,
    source: ['祈願'],
    use: '用於夜晚、夢境或情緒相關的魔法商品；之後可作為煉金高階材料。',
    description: '夜晚天空中掉落的碎片，彷彿封存了一小段星空。常用於與夜晚、夢境或情緒相關的魔法。',
  },
  forest_cookie: {
    id: 'forest_cookie',
    name: '森林餅乾',
    icon: '🍪',
    type: 'sweet',
    typeName: '甜點',
    rarity: 'R',
    stars: 2,
    source: ['祈願', '後山'],
    use: '普通委託常見的小甜點，也能作為廚房產品的基底。',
    description: '烤成葉片形狀的小餅乾，帶著淡淡蜂蜜與木質香。',
  },
  stardew_water: {
    id: 'stardew_water',
    name: '星露水',
    icon: '💧',
    type: 'material',
    typeName: '素材',
    rarity: 'R',
    stars: 3,
    source: ['祈願', '簽到', '後山', '溫室'],
    use: '澆灌魔法植物，或作為飲品與煉成的基底。',
    description: '清晨凝在花瓣上的露水，映著細小星光。',
  },
  moon_latte: {
    id: 'moon_latte',
    name: '月光花瓣拿鐵',
    icon: '☕',
    type: 'drink',
    typeName: '飲品',
    rarity: 'SR',
    stars: 5,
    source: ['廚房製作', '委託獎勵'],
    use: '安定系飲品，可用於溫柔、祝福、月光主題委託。',
    description: '溫柔發光的奶泡像一層薄薄月色，喝下後心情會慢慢安定。',
  },
  star_berry_tart: {
    id: 'star_berry_tart',
    name: '星星莓奶油塔',
    icon: '🥧',
    type: 'sweet',
    typeName: '甜點',
    rarity: 'R',
    stars: 4,
    source: ['廚房製作', '委託獎勵'],
    use: '好運與活力主題委託常用甜點。',
    description: '星星莓鋪在奶油塔上，切開時會掉出一點金色糖屑。',
  },
  dream_cocoa: {
    id: 'dream_cocoa',
    name: '夜空碎片可可',
    icon: '🍫',
    type: 'drink',
    typeName: '飲品',
    rarity: 'SR',
    stars: 5,
    source: ['廚房製作', '委託獎勵'],
    use: '夢境、夜晚與安眠主題委託常用飲品。',
    description: '把夜空碎片融進可可裡，杯面會浮出一小片安靜星空。',
  },
  moon_dew: {
    id: 'moon_dew',
    name: '月光露珠',
    icon: '🌙',
    type: 'refined_material',
    typeName: '煉成素材',
    tier: 2,
    rarity: 'SR',
    stars: 5,
    source: ['煉金室製作'],
    use: '月光、祝福與安定系商品的二階素材。',
    description: '把月光花瓣與星露水慢慢煉成的透明露珠，會在瓶底映出一圈柔光。',
  },
  star_berry_syrup: {
    id: 'star_berry_syrup',
    name: '星莓糖漿',
    icon: '🍯',
    type: 'refined_material',
    typeName: '煉成素材',
    tier: 2,
    rarity: 'R',
    stars: 4,
    source: ['煉金室製作'],
    use: '甜點、飲品與好運主題商品的二階素材。',
    description: '星星莓熬成的金紅色糖漿，搖晃時會出現細小星屑。',
  },
  dream_essence: {
    id: 'dream_essence',
    name: '夢境精華',
    icon: '💤',
    type: 'refined_material',
    typeName: '煉成素材',
    tier: 2,
    rarity: 'SR',
    stars: 5,
    source: ['煉金室製作'],
    use: '夢境、夜晚與情緒主題商品的二階素材。',
    description: '夜空碎片在星露水中沉澱後留下的精華，像一小團安靜的夢。',
  },
  pure_moon_essence: {
    id: 'pure_moon_essence',
    name: '純月精華',
    icon: '✨',
    type: 'refined_material',
    typeName: '三階煉成素材',
    tier: 3,
    rarity: 'SSR',
    stars: 5,
    source: ['煉金室製作'],
    use: '高階月光、祝福與夢境商品的核心材料。',
    description: '將月光露珠與夜空碎片再次穩定化後形成的精華，像把一整晚的月色濃縮成一滴光。',
  },
};

export const itemSources = {
  moon_petals: { type: 'scene', id: 'greenhouse' },
  star_berry: { type: 'scene', id: 'backyard' },
  night_sky_fragment: { type: 'route', id: 'gacha' },
  forest_cookie: { type: 'scene', id: 'backyard' },
  stardew_water: { type: 'scene', id: 'backyard' },
  moon_latte: { type: 'station', id: 'kitchen' },
  star_berry_tart: { type: 'station', id: 'kitchen' },
  dream_cocoa: { type: 'station', id: 'kitchen' },
  moon_dew: { type: 'station', id: 'alchemy' },
  star_berry_syrup: { type: 'station', id: 'alchemy' },
  dream_essence: { type: 'station', id: 'alchemy' },
  pure_moon_essence: { type: 'station', id: 'alchemy' },
};
